name: calculadora_clt_x_pj
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/